"""
Enhanced report generation service.
Generates professional PDF and HTML legal reports.
"""

import datetime
import logging
from fpdf import FPDF

logger = logging.getLogger(__name__)


class LegalReportPDF(FPDF):
    """Enhanced FPDF subclass for professional legal reports."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Arial", "B", 14)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, "LAWGIC - Legal Intelligence Report", ln=True, align="C")
        self.set_font("Arial", "", 8)
        self.set_text_color(127, 140, 141)
        self.cell(0, 5, f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(149, 165, 166)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | LAWGIC Legal Intelligence Platform", align="C")

    def section_title(self, title):
        self.set_font("Arial", "B", 12)
        self.set_text_color(41, 128, 185)
        self.cell(0, 10, title, ln=True)
        self.set_draw_color(41, 128, 185)
        self.line(self.get_x(), self.get_y(), self.get_x() + 60, self.get_y())
        self.ln(3)

    def body_text(self, text):
        self.set_font("Arial", "", 10)
        self.set_text_color(51, 51, 51)
        safe_text = text.encode('latin-1', 'replace').decode('latin-1')
        self.multi_cell(0, 6, safe_text)
        self.ln(3)

    def add_case_card(self, case):
        self.set_font("Arial", "B", 10)
        self.set_text_color(44, 62, 80)
        safe_title = case.get("case_title", "").encode('latin-1', 'replace').decode('latin-1')
        self.cell(0, 7, safe_title[:80], ln=True)

        self.set_font("Arial", "I", 9)
        self.set_text_color(127, 140, 141)
        court = case.get("court", "Unknown Court")
        score = case.get("similarity_score", 0)
        self.cell(0, 5, f"Court: {court} | Relevance: {score:.0%}", ln=True)

        self.set_font("Arial", "", 9)
        self.set_text_color(51, 51, 51)
        summary = case.get("summary", "")[:300]
        safe_summary = summary.encode('latin-1', 'replace').decode('latin-1')
        self.multi_cell(0, 5, safe_summary)

        source_url = case.get("source_url", "")
        if source_url:
            self.set_font("Arial", "U", 8)
            self.set_text_color(41, 128, 185)
            safe_url = source_url.encode('latin-1', 'replace').decode('latin-1')
            self.cell(0, 5, safe_url, ln=True, link=source_url)

        sections = case.get("sections", [])
        if sections:
            self.set_font("Arial", "", 8)
            self.set_text_color(127, 140, 141)
            self.cell(0, 5, f"Sections: {', '.join(str(s) for s in sections)}", ln=True)

        self.ln(5)


def generate_pdf(analysis, user_case, similar_cases=None):
    """
    Generate an enhanced PDF legal report.

    Args:
        analysis: The AI legal analysis text.
        user_case: The original case description.
        similar_cases: Optional list of similar case dicts.

    Returns:
        bytes: The PDF file content.
    """
    pdf = LegalReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.section_title("Case Description")
    pdf.body_text(user_case)

    pdf.section_title("AI Legal Analysis")
    pdf.body_text(analysis)

    if similar_cases:
        pdf.add_page()
        pdf.section_title(f"Similar Cases ({len(similar_cases)} found)")

        for i, case in enumerate(similar_cases, 1):
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(44, 62, 80)
            pdf.cell(0, 7, f"Case {i}:", ln=True)
            if isinstance(case, dict):
                pdf.add_case_card(case)
            else:
                pdf.add_case_card(case.to_dict())

    pdf.ln(10)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(231, 76, 60)
    pdf.multi_cell(
        0, 5,
        "DISCLAIMER: This report is generated by an AI system for academic and research "
        "purposes only. It does not constitute professional legal advice."
    )

    pdf_output = pdf.output(dest="S")
    return pdf_output.encode("latin-1", "ignore")


def generate_html_report(analysis, user_case, similar_cases=None):
    """
    Generate a printable HTML report.

    Args:
        analysis: The AI legal analysis text.
        user_case: The original case description.
        similar_cases: Optional list of similar case dicts.

    Returns:
        str: HTML report content.
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    cases_html = ""
    if similar_cases:
        for i, case in enumerate(similar_cases, 1):
            if not isinstance(case, dict):
                case = case.to_dict()
            score_pct = int(case.get("similarity_score", 0) * 100)
            if score_pct >= 70:
                score_color = "#27ae60"
            elif score_pct >= 40:
                score_color = "#f39c12"
            else:
                score_color = "#e74c3c"

            sections_str = ", ".join(str(s) for s in case.get("sections", []))
            source_url = case.get("source_url", "#")

            cases_html += f"""
            <div style="border:1px solid #e0e0e0;border-radius:8px;padding:20px;margin-bottom:15px;background:#fafafa;">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;">
                    <h3 style="margin:0;font-size:15px;color:#2c3e50;">Case {i}: {case.get("case_title", "Unknown")}</h3>
                    <span style="background-color:{score_color};color:white;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:600;">
                        {score_pct}% Match
                    </span>
                </div>
                <p style="font-size:13px;color:#7f8c8d;font-style:italic;">{case.get("court", "Unknown Court")}</p>
                <p style="font-size:13px;margin:10px 0;color:#555;">{case.get("summary", "")[:400]}</p>
                {"<p style='font-size:12px;color:#7f8c8d;'>Sections: " + sections_str + "</p>" if sections_str else ""}
                <a href="{source_url}" target="_blank" style="font-size:13px;color:#2980b9;text-decoration:none;">View Full Case &rarr;</a>
            </div>
            """

    analysis_html = analysis.replace("\n", "<br>")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LAWGIC Legal Report</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Inter', sans-serif; color: #2c3e50; background: #f8f9fa; line-height: 1.6; }}
        .report-container {{ max-width: 800px; margin: 0 auto; background: white; padding: 50px; }}
        .report-header {{ text-align: center; border-bottom: 3px solid #2c3e50; padding-bottom: 20px; margin-bottom: 30px; }}
        .report-header h1 {{ font-size: 28px; color: #2c3e50; letter-spacing: 3px; }}
        .report-header .subtitle {{ color: #7f8c8d; font-size: 14px; margin-top: 5px; }}
        .section {{ margin-bottom: 30px; }}
        .section h2 {{ font-size: 18px; color: #2980b9; border-left: 4px solid #2980b9; padding-left: 12px; margin-bottom: 15px; }}
        .section-content {{ padding-left: 16px; font-size: 14px; }}
        .disclaimer {{ margin-top: 40px; padding: 15px; background: #fdf2f2; border-left: 4px solid #e74c3c; font-size: 12px; color: #e74c3c; }}
        @media print {{ body {{ background: white; }} .report-container {{ padding: 20px; }} }}
    </style>
</head>
<body>
    <div class="report-container">
        <div class="report-header">
            <h1>LAWGIC</h1>
            <p class="subtitle">AI-Powered Legal Intelligence Report | {now}</p>
        </div>
        <div class="section">
            <h2>Case Description</h2>
            <div class="section-content"><p>{user_case}</p></div>
        </div>
        <div class="section">
            <h2>AI Legal Analysis</h2>
            <div class="section-content"><p>{analysis_html}</p></div>
        </div>
        {"<div class='section'><h2>Similar Cases (" + str(len(similar_cases)) + " found)</h2>" + cases_html + "</div>" if similar_cases else ""}
        <div class="disclaimer">
            <strong>DISCLAIMER:</strong> This report is generated by an AI system for academic
            and research purposes only. It does not constitute professional legal advice.
        </div>
    </div>
</body>
</html>"""

    return html
